// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "Authentication API": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=ryan/design
// --out=$(GOPATH)\src\ryan
// --version=v1.3.1

package app
